### ISSUE TITLE
Consensus maker 

### ISSUE THREAD

**Issue by arnavaz** [loeblab/Duplex-Sequencing#16]
Hi,
I am running the Consensus make script as part of the duplex pipeline. But I do not see the .UP.bam file and the tagcounts file being generated. I need to know why these files are absent. I have the LCC.bam and the NM.bam and DCS.bam files.
Thank you,

Arnavaz

**Comment by scottrk** [comment]
The UP.bam file will only be generated if the 'd' option is enabled in 
the --read_type option. As for the tagcounts file, it's being generated 
for me. I'm not seeing issues with that. Double check if that's true.

**Comment by arnavaz** [comment]
Thanks for the reply! So, if the tagcounts file is absent, could that mean the pipeline is not woking properly?

**Comment by arnavaz** [comment]
I also have the d option enabled, but still not getting the .Up.bam file. What could that mean?

**Comment by scottrk** [comment]
I think I may have found the bug, but I have question first. What is the file name you are giving the --tagfile option for ConsensusMaker.py?

## 

Scott R. Kennedy, Ph.D.
HSB K-058, Box 357705
Dept. of Pathology
University of Washington-Seattle
Seattle, WA 98195-7705

Phone: (206)543-0557

**Comment by arnavaz** [comment]
It's "Sample_DS-B100.tagcount". And thanks for the follow-up!

**Comment by scottrk** [comment]
Ah ha! Try naming it Sample_DS-B100.tagcounts and see if it works for you.  That will be an interim fix until I figure out the best way to fix this in a well behaved manner.

## Scott

Scott R. Kennedy, Ph.D.
HSB K-058, Box 357705
Dept. of Pathology
University of Washington-Seattle
Seattle, WA 98195-7705

Phone: (206)543-0557

**Comment by arnavaz** [comment]
I have to add that the above .tagcount file is created but it is 0 bytes. If this helps.

**Comment by arnavaz** [comment]
Ok! I will try and will let you know! Thanks again!

**Comment by scottrk** [comment]
I made a fix on the github repository. You may want to do a pull and see 
if that works for you.

Scott

**Comment by arnavaz** [comment]
I ran the pipeline again. It worked for the tagcounts file. But the .UP.bam files is still not created. Could this be due to my data type or this can be fixed too?
Thank you!

Arnavaz

**Comment by scottrk** [comment]
The UP file will only be created when both the 'd' filter is invoked at 
a --isize (i.e. insert size) option is > -1. I don't remember the logic 
behind this and I never use it. It's definitely not used by anyone in my 
lab.

Scott

**Comment by arnavaz** [comment]
I see! Thank you very much!

**Comment by arnavaz** [comment]
Hi Scott! 
I just had another questions. Why are there so many reads take away as "NUM.bam" file. What does a bad read mean? In the first round of alignment with bwa I get a big bam file with aligned reads. But a lot of them get filtered out as "*NM.bam". Could you please tell me why? Thank you again!
Arnavaz

**Comment by scottrk** [comment]
NM.bam is where unmapped reads go. They don't go on to form a 
consensus.  The logic for splitting those off is to prevent reads that 
start off well and have a well formed tag, but then fail somewhere along 
the way, from contributing to a consensus. They'll just mess things up.  
"Bad reads" is kind of a catch all term, which basically means a read 
has a FLAG that doesn't make any sense. We've run across instances where 
a read will be designated contradictory things(i.e. designated single 
end, but also properly paired). They form nonsensical FLAG values and so 
we just assume something is wrong with them.

Now, for why _your_ data is being put into the nonmapping file, I can't 
tell you. You'll get lots of those if your run was overclustered or was 
of otherwise poor quality.  Having contaminating DNA that doesn't align 
against your reference genome will do that, as well.  For instance, if I 
am sequencing human mtDNA and I align it against to only the mtDNA, then 
all the nuclear mapping reads will be considered unmapped.  It really is 
specific to the experimental system you're working with.

Hope that helps,
Scott

**Comment by arnavaz** [comment]
Thanks Scott! That helps.
Our data is circulating DNA. I need to figure our why there is so many bad reads stored in my UM.bam. 
Arnavaz

**Comment by scottrk** [comment]
Closing as resolved.
